[auth]
url = "{{ urls.auth }}"
type = "bearer"
headers = ["username", "$password"]
token_path = "data.token"

[urls]
auth = { url = "/admin/index.php?route=api/auth", fields = [
    'username',
    'password',
], method = "POST" }
ping = "/admin/index.php?route=api/ping"
option_ping = "/admin/index.php?route=api/ping"

[urls.order]
details = "/admin/index.php?route=api/order/details&order_id={{ order_id }}"
list = "/admin/index.php?route=api/order/list"
pre-fetch = "/admin/index.php?route=api/order/preFetchShippingLabel&order_ids={{ order_ids }}"
pick = { url = "/admin/index.php?route=api/order/pick&order_id={{ order_id }}", method = "POST" }
ship = { url = "/admin/index.php?route=api/order/ship&order_id={{ order_id }}", method = "POST" }
