[auth]
url=":auth"
type="bearer"
headers=["username", "$password"]
token_path="data.token"

[urls]
auth="/admin/index.php?route=api/auth"
ping="/admin/index.php?route=api/ping"

[urls.order]
details="/admin/index.php?route=api/order/details&order_id={{ order_id }}&other={{ other }}"
list="/admin/index.php?route=api/order/list"
ship={ url = "/admin/index.php?route=api/order/ship", method = "POST" }
